# -*- coding: utf-8 -*-
"""LSDP DA 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10kxvIpQco8hYlNkYu9wLjNk1d3a4r11M

# **Implementation of AdaBoost Algorithm**
"""

# Load libraries

from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

import pandas as pd
# Load data
LoanData=pd.read_csv("/content/income.csv")
LoanData.head()

#Seperating predictors and response
X=LoanData.iloc[:,0:6]
y=LoanData.iloc[:,6]

#Split dataset into traning and test set
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

#Create adaboost classifier object
AdaModel= AdaBoostClassifier(n_estimators=100, learning_rate=1.0)

#Train adaboost classifier
model= AdaModel.fit(X_train,y_train)

#Predict the response for test dataset
y_pred= model.predict(X_test)

#Model accuracy
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))